version: "3"

services:
  payload:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "pnpm install && pnpm dev"
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - cms-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    networks:
      - cms-network

volumes:
  data:
  node_modules:

networks:
  cms-network:
    driver: bridge
